apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamops-ui
  namespace: teamops
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: teamops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teamops-ui
                port:
                  number: 80
